
const ContentSaladePrensa = {
  en: [
    {
      id: 1,
      title: "First International Congress of Environmental Organizations in Manizales",
      category: "Digital",
      date: "July 9, 2024",
      shortdescription: "Manizales becomes the World Capital in the Fight Against Climate Change and Environmental Conservation",
      bannerUrl: "https://example.com",
      bannerAlt: "First International Congress of Environmental Organizations",
      bannerdescription: "",
      articlesocialmedia: {
        facebook: "Facebook",
        twitter: "",
        instagram: "",
        linkedin: "",
        youtube: "",
        telegram: "Telegram",
        whatsapp: "WhatsApp",
        email: "Email"
      },
      media: {
        name: "Communication Unit of UAM",
        logoUrl: "https://example.com",
        logoAlt: "Communication Unit of UAM",
        socialmedia: {
          web: "",
          facebook: "",
          twitter: "",
          instagram: "",
          linkedin: "",
          youtube: "",
        }, 
      },
      subtitle: [
        ["Manizales becomes the World Capital in the Fight Against Climate Change and Environmental Conservation"],
      ],
      audiotitle: "",
      audioUrl: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1874778714&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lapatriaradio" title="LaPatriaRadio" target="_blank" style="color: #cccccc; text-decoration: none;">LaPatriaRadio</a> · <a href="https://soundcloud.com/lapatriaradio/9-entrevista-con-jose-serrano-serna-presidente-de-awaq-18-de-julio" title="9. Entrevista Con Jose  Serrano Serna, Presidente De Awaq. - 18 De Julio" target="_blank" style="color: #cccccc; text-decoration: none;">9. Entrevista Con Jose  Serrano Serna, Presidente De Awaq. - 18 De Julio</a></div>',
      titledescription: "Manizales will host the First International Congress of Environmental Organizations, a landmark event in the fight against climate change and the conservation of our planet.",
      paragraph: [
        ["From August 20 to 23, 2024, around 100 environmental organizations will gather at the Autonomous University of Manizales, thanks to the collaboration between Awaq Estaciones Biológicas, the Autonomous University of Manizales, and the Society of Doctors and Researchers of Colombia (SoPhIC)."],
        ["The main goal of the congress is to unite efforts between project-managing organizations, sustainability experts, and public and private entities to create a greener and more conscious future. The congress aims to: generate strategic alliances; find innovative solutions to combat climate change; foster collaboration between universities, public bodies, and private companies."],
        ["Thematic Lines: Sources of Funding for Environmental Projects: Identification and access to funds and resources to support sustainability projects; Biodiversity Conservation: Projects and practices to preserve and restore ecosystems; Innovation in Sustainability: Development and application of green technologies; Education and Awareness: Workshops and conferences to educate and mobilize the global community; Policies and Regulations: Discussion on public policies and regulations supporting environmental sustainability."],
        ["Presentation of the Manifesto: During the congress, a manifesto will be signed and presented to the United Nations Economic and Social Council (ECOSOC) by Awaq ONGD in its capacity as a consultative member. This document will reflect our commitment and the necessary actions to drive the transition towards a more sustainable world."],
        ["Registration: Interested parties can register at the following link: Congress Registration"],
        ["Why attend? Forge Powerful Alliances: Connect with universities, public bodies, and private entities dedicated to environmental sustainability; Innovate and Collaborate: Discover cutting-edge solutions and collaborate on projects that will impact the future of conservation; Be Part of a Movement: Join a community of people and organizations passionate about making a real difference."],
        ["It will be a unique opportunity to be part of a movement that will define the future of environmental conservation in Colombia and beyond, highlights the Communication Unit of UAM."]
      ],
      videoUrl: "",
      videoAlt: "",
      videodescription: "",
      gallery: [],
      iframe: [],
    },
    {
      id: 2,
      title: "1st International Congress of Environmental Organizations to be Held in Manizales",
      category: "Event",
      date: "2024-07-18",
      shortdescription: "The congress will take place in Manizales from August 20 to 23, 2024. Learn more at congresoawaq.org",
      bannerUrl: "https://example.com",
      bannerAlt: "International Congress of Environmental Organizations",
      bannerdescription: "Photo | LA PATRIA",
      articlesocialmedia: {
        facebook: "Facebook",
        twitter: "Twitter",
        instagram: "",
        linkedin: "",
        youtube: "",
        telegram: "",
        whatsapp: "WhatsApp",
        email: ""
      },
      media: {
        name: "lapatria.com",
        logoUrl: "https://example.com",
        logoAlt: "LA PATRIA",
        socialmedia: {
          web: "",
          facebook: "",
          twitter: "",
          instagram: "",
          linkedin: "",
          youtube: "",
        }, 
      },
      subtitle: [
        ["The congress will take place in Manizales from August 20 to 23, 2024. Learn more at congresoawaq.org"]
      ],
      audiotitle: "",
      audioUrl: "https://example.com",
      titledescription: "José Serrano Serna, President of Awaq ONGD, spoke with LA PATRIA Radio about the first International Congress of Environmental Organizations to be held in Manizales from August 20 to 23.",
      paragraph: [
        ["What is the event about? José Serrano explained that the congress aims to create a forum for environmental organizations to discuss common issues, obstacles to growth, and collaborate on solutions. He emphasized the importance of having a space where all organizations are the main players and can engage with key stakeholders that influence their operations."],
        ["What will happen at this first congress? The congress will address four key areas: access to funding, lack of representation in public administrations, technology access and training, and the role of private enterprise in environmental conservation. These discussions aim to share best practices and improve conservation programs."],
        ["Why are these spaces important? Colombia is the second most biodiverse country in the world, which underscores the importance of creating a united network of organizations to preserve this global heritage. The congress seeks to increase the visibility of environmental organizations and highlight their role in influencing policies and conservation projects."],
        ["The full interview can be listened to here: [link to interview]"]
      ],
      videoUrl: "",
      videoAlt: "",
      videodescription: "",
      gallery: [],
      iframe: [],
    },
    {
      id: 3,
      title: "Interview with Bellzmín Arenas Quintana, Coordinator of the Social Projection Unit at the Autonomous University of Manizales",
      category: "Interview",
      date: "2024-07-16",
      shortdescription: "An interview with Bellzmín Arenas Quintana, discussing the role of the university in social projection and community engagement.",
      bannerUrl: "https://example.com",
      bannerAlt: "Interview with Bellzmín Arenas Quintana",
      bannerdescription: "Photo | Tropicana",
      articlesocialmedia: {
        facebook: "Facebook",
        twitter: "Twitter",
        instagram: "",
        linkedin: "",
        youtube: "",
        telegram: "",
        whatsapp: "",
        email: ""
      },
      media: {
        name: "Tropicana",
        logoUrl: "https://example.com",
        logoAlt: "Tropicana",
        socialmedia: {
          web: "",
          facebook: "",
          twitter: "",
          instagram: "",
          linkedin: "",
          youtube: "",
        }, 
      },
      subtitle: [
        ["Interview with Bellzmín Arenas Quintana, Coordinator of the Social Projection Unit at the Autonomous University of Manizales."]
      ],
      audiotitle: "",
      audioUrl: "https://example.com",
      titledescription: "Bellzmín Arenas Quintana, Coordinator of the Social Projection Unit, shares insights on the university's initiatives to engage with the community and contribute to social development.",
      paragraph: [
        ["During the interview, Bellzmín Arenas Quintana discussed the university's commitment to social responsibility and how it plays a crucial role in addressing local community needs. The Social Projection Unit focuses on developing projects that not only enhance academic learning but also provide meaningful contributions to society."],
        ["Quintana highlighted several ongoing projects, including educational outreach programs, environmental sustainability initiatives, and partnerships with local organizations to foster community development. She emphasized the importance of integrating academic knowledge with practical applications to create a positive impact."],
        ["The interview also touched on future plans for expanding the unit's activities and enhancing collaborations with various stakeholders, including NGOs, government agencies, and private sector partners. Quintana expressed optimism about the potential for these initiatives to create lasting change and improve the quality of life for the people in the region."]
      ],
      videoUrl: "",
      videoAlt: "",
      videodescription: "",
      gallery: [],
      iframe: [],
    },
    {
      id: 4,
      title: "RCN Radio Manizales 1,060 AM Broadcasts Live on the International Congress of Environmental Organizations",
      category: "Broadcast",
      date: "2024-07-12",
      shortdescription: "RCN Radio Manizales aired a live broadcast discussing the upcoming International Congress of Environmental Organizations.",
      bannerUrl: "https://example.com",
      bannerAlt: "RCN Radio Manizales",
      bannerdescription: "Photo | RCN Radio",
      articlesocialmedia: {
        facebook: "Facebook",
        twitter: "Twitter",
        instagram: "",
        linkedin: "",
        youtube: "",
        telegram: "",
        whatsapp: "",
        email: ""
      },
      media: {
        name: "RCN Radio Manizales",
        logoUrl: "https://example.com",
        logoAlt: "RCN Radio Manizales",
        socialmedia: {
          web: "",
          facebook: "",
          twitter: "",
          instagram: "",
          linkedin: "",
          youtube: "",
        }, 
      },
      subtitle: [
        ["RCN Radio Manizales 1,060 AM aired a live broadcast discussing the upcoming International Congress of Environmental Organizations."]
      ],
      audiotitle: "",
      audioUrl: "https://example.com",
      titledescription: "Victoria Salazar Gil, Coordinator of Specialization in Formulation, Management, and Evaluation of Development Projects, and Coordinator of Social Practice, shared insights on the significance of the Congress for environmental organizations and the community.",
      paragraph: [
        ["Victoria Salazar Gil discussed the role of the congress in fostering collaboration among environmental organizations and stakeholders. She highlighted the importance of such events in promoting awareness, sharing knowledge, and developing joint initiatives to address environmental challenges."],
        ["Salazar Gil emphasized that the congress will provide a platform for organizations to present their projects, seek partnerships, and explore funding opportunities. The event aims to strengthen the network of environmental organizations and enhance their capacity to implement impactful projects."],
        ["The live broadcast also covered the key themes of the congress, including funding sources for environmental projects, biodiversity conservation, sustainability innovation, education, and policy discussions. The event is expected to attract a diverse audience, including researchers, policymakers, and activists."]
      ],
      videoUrl: "",
      videoAlt: "",
      videodescription: "",
      gallery: [],
      iframe: [],
    },
    {
      id: 5,
      title: "1st International Congress of Environmental Organizations to be Held at UAM",
      category: "Internationalization",
      date: "2024-07-19",
      shortdescription: "The University of Manizales (UAM) will host the 1st International Congress of Environmental Organizations, a historic event that will position Manizales as the global capital in the fight against climate change and environmental conservation.",
      bannerUrl: "https://example.com",
      bannerAlt: "UAM Conference",
      bannerdescription: "Photo | UAM",
      articlesocialmedia: {
        facebook: "Facebook",
        twitter: "Twitter",
        instagram: "",
        linkedin: "",
        youtube: "",
        telegram: "",
        whatsapp: "",
        email: ""
      },
      media: {
        name: "UAM",
        logoUrl: "https://example.com",
        logoAlt: "University of Manizales",
        socialmedia: {
          web: "",
          facebook: "",
          twitter: "",
          instagram: "",
          linkedin: "",
          youtube: "",
        }, 
      },
      subtitle: [
        ["The University of Manizales (UAM) will host the 1st International Congress of Environmental Organizations, a historic event that will position Manizales as the global capital in the fight against climate change and environmental conservation."]
      ],
      audiotitle: "",
      audioUrl: "https://example.com",
      titledescription: "From August 20 to 23, 2024, nearly 100 environmental organizations will gather in Manizales, Caldas, thanks to the collaboration between Awaq Biological Stations, the University of Manizales, and the Society of Doctors and Researchers of Colombia (SoPhIC).",
      paragraph: [
        ["The 1st International Congress of Environmental Organizations aims to bring together project management organizations, sustainability experts, and public and private entities to create a greener and more conscious future. The event will focus on:"],
        ["- Forming strategic alliances.", "- Developing innovative solutions to combat climate change.", "- Promoting collaboration between universities, public agencies, and private companies."],
        ["Key themes of the congress include:"],
        ["- **Sources of Funding for Environmental Projects**: Identifying and accessing funds and resources to support sustainability projects.", "- **Biodiversity Conservation**: Projects and practices to preserve and restore ecosystems.", "- **Sustainability Innovation**: Developing and applying green technologies.", "- **Education and Awareness**: Workshops and conferences to educate and mobilize the global community.", "- **Policies and Regulations**: Discussion on public policies and regulations supporting environmental sustainability."],
        ["During the congress, a manifesto will be signed and presented to the United Nations Economic and Social Council (ECOSOC) by Awaq ONGD as a consultative member. This document will reflect our commitment and the necessary actions to drive the transition towards a more sustainable world."],
        ["Those interested can register [here](https://example.com)."],
        ["**Why attend the 1st International Congress of Environmental Organizations?**"],
        ["- Forge powerful alliances: Connect with universities, public agencies, and private entities dedicated to environmental sustainability.", "- Innovate and collaborate: Discover cutting-edge solutions and collaborate on projects that will impact the future of conservation.", "- Be part of a movement: Join a community of people and organizations passionate about making a real difference."],
        ["Don't miss this unique opportunity to be part of a movement that will define the future of environmental conservation in Colombia and beyond."]
      ],
      videoUrl: "",
      videoAlt: "",
      videodescription: "",
      gallery: [],
      iframe: [],
    },
  ],
  es: [
    {
      id: 1,
      title: "Primer Congreso Internacional de Organizaciones Ambientales en Manizales",
      category: "Digital",
      date: "2024-07-09",
      shortdescription: "Manizales se convierte en la Capital Mundial de la Lucha Contra el Cambio Climático y la Conservación Ambiental",
      bannerUrl: "https://www.autonoma.edu.co/sites/default/files/2024-07/congreso-internacional-organizaciones-ambientales-uam.jpg",
      bannerAlt: "Primer Congreso Internacional de Organizaciones Ambientales",
      bannerdescription: "",
      articlesocialmedia: {
        facebook: "",
        twitter: "",
        instagram: "",
        linkedin: "",
        youtube: "",
        telegram: "",
        whatsapp: "",
        email: ""
      },
      media: {
        name: "Unidad de Comunicaciones de la UAM",
        logoUrl: "https://www.autonoma.edu.co/sites/default/files/Universidad_Autonoma_de_Manizales.png",
        logoAlt: "Unidad de Comunicaciones de la UAM",
        socialmedia: {
          web: "https://www.autonoma.edu.co/blog/noticias/1er-congreso-internacional-de-organizaciones-ambientales-con-sede-en-la-uam",
          facebook: "https://www.facebook.com/UAMManizales",
          twitter: "https://twitter.com/UAMManizales",
          instagram: "https://www.instagram.com/uammanizales",
          linkedin: "",
          youtube: "",
        },
      },
      subtitle: [
        ["Manizales se convierte en la Capital Mundial de la Lucha Contra el Cambio Climático y la Conservación Ambiental"],
      ],
      audiotitle: "",
      audioUrl: "",
      titledescription: "Manizales será la sede del Primer Congreso Internacional de Organizaciones Ambientales, un certamen que marcará un precedente histórico en la lucha contra el cambio climático y la conservación de nuestro planeta.",
      paragraph: [
        ["Del 20 al 23 de agosto de 2024, cerca de 100 organizaciones ambientales se reunirán en la Universidad Autónoma de Manizales, gracias a la colaboración entre Awaq Estaciones Biológicas, la Universidad Autónoma de Manizales y la Sociedad de Doctores e Investigadores de Colombia (SoPhIC)."],
        ["El objetivo principal del congreso es unir esfuerzos entre organizaciones gestoras de proyectos, expertos en sostenibilidad y entidades públicas y privadas para crear un futuro más verde y consciente. Se buscará: generar alianzas estratégicas; encontrar soluciones innovadoras para combatir el cambio climático; fomentar la colaboración entre universidades, organismos públicos y empresas privadas."],
        ["Líneas Temáticas: Fuentes de Financiación de Proyectos Ambientales: Identificación y acceso a fondos y recursos para apoyar proyectos de sostenibilidad; Conservación de la Biodiversidad: Proyectos y prácticas para preservar y restaurar ecosistemas; Innovación en Sostenibilidad: Desarrollo y aplicación de tecnologías verdes; Educación y Sensibilización: Talleres y conferencias para educar y movilizar a la comunidad global; Políticas y Regulaciones: Discusión sobre políticas públicas y regulaciones que apoyen la sostenibilidad ambiental."],
        ["Presentación del Manifiesto: Durante el congreso, se firmará un manifiesto que será presentado al Consejo Económico y Social de las Naciones Unidas (ECOSOC) por Awaq ONGD en su calidad de miembro consultivo. Este documento reflejará nuestro compromiso y las acciones necesarias para impulsar la transición hacia un mundo más sostenible."],
        ["Registro: Los interesados pueden registrarse en el siguiente enlace: Registro Congreso"],
        ["¿Por qué asistir? Forja Alianzas Poderosas: Conecta con universidades, organismos públicos y entidades privadas dedicadas a la sostenibilidad ambiental; Innova y Colabora: Descubre soluciones vanguardistas y colabora en proyectos que impactarán el futuro de la conservación; Sé Parte de un Movimiento: Únete a una comunidad de personas y organizaciones apasionadas por hacer una diferencia real."],
        ["Será una oportunidad única de ser parte de un movimiento que definirá el futuro de la conservación ambiental en Colombia y más allá, destaca la Unidad de Comunicaciones de la UAM."]
      ],
      videoUrl: "",
      videoAlt: "",
      videodescription: "",
      gallery: [],
      iframe: [],
    },
    {
      id: 2,
      title: "1° Congreso Internacional de Organizaciones Ambientales será en Manizales, conozca cuándo",
      category: "Evento",
      date: "2024-07-18",
      shortdescription: "El congreso será en Manizales del 20 al 23 de agosto y pueden participar en congresoawaq.org",
      bannerUrl: "https://www.tropicanafm.com/wp-content/uploads/2022/02/GettyImages-1301663422.jpg",
      bannerAlt: "Congreso Internacional de Organizaciones Ambientales",
      bannerdescription: "Foto | LA PATRIA",
      articlesocialmedia: {
        facebook: "",
        twitter: "",
        instagram: "",
        linkedin: "",
        youtube: "",
        telegram: "",
        whatsapp: "",
        email: ""
      },
      media: {
        name: "LA PATRIA",
        logoUrl: "https://www.lapatria.com/sites/default/files/media-library/2022-05/logo%20LP%20azul.svg",
        logoAlt: "LA PATRIA",
        socialmedia: {
          web: "https://www.lapatria.com/manizales/1deg-congreso-internacional-de-organizaciones-ambientales-sera-en-manizales-conozca",
          facebook: "https://www.lapatria.com/sites/default/files/inline-images/facebook.png",
          twitter: "https://twitter.com/lapatriacom",
          instagram: "https://www.instagram.com/lapatriacom",
          linkedin: "",
          youtube: "https://www.lapatria.com/sites/default/files/inline-images/youtube_0.png",
        }, 
      },
      subtitle: [
        ["El congreso será en Manizales del 20 al 23 de agosto y pueden participar en congresoawaq.org"]
      ],
      audiotitle: "",
      audioUrl: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1874778714&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lapatriaradio" title="LaPatriaRadio" target="_blank" style="color: #cccccc; text-decoration: none;">LaPatriaRadio</a> · <a href="https://soundcloud.com/lapatriaradio/9-entrevista-con-jose-serrano-serna-presidente-de-awaq-18-de-julio" title="9. Entrevista Con Jose  Serrano Serna, Presidente De Awaq. - 18 De Julio" target="_blank" style="color: #cccccc; text-decoration: none;">9. Entrevista Con Jose  Serrano Serna, Presidente De Awaq. - 18 De Julio</a></div>',
      titledescription: "José Serrano Serna, presidente de Awaq ONGD, habló con LA PATRIA Radio sobre el primer Congreso Internacional de Organizaciones Ambientales que se hará en Manizales del 20 al 23 de agosto.",
      paragraph: [
        ["¿De qué se trata el evento? José Serrano explicó que el congreso tiene como objetivo crear un foro para que las organizaciones ambientales discutan problemas comunes, obstáculos para el crecimiento y colaboren en soluciones. Destacó la importancia de tener un espacio donde todas las organizaciones sean las protagonistas y puedan interactuar con actores clave que influyen en sus operaciones."],
        ["¿Qué va a suceder en este primer congreso? El congreso abordará cuatro áreas clave: acceso a la financiación, falta de representación en las administraciones públicas, acceso y formación en tecnología, y el papel de la empresa privada en la conservación ambiental. Estas discusiones buscan compartir buenas prácticas y mejorar los programas de conservación."],
        ["¿Cuál es la relevancia de estos espacios? Colombia es el segundo país más biodiverso del mundo, lo que subraya la importancia de crear una red unida de organizaciones para preservar este patrimonio global. El congreso busca aumentar la visibilidad de las organizaciones ambientales y destacar su papel en la influencia de políticas y proyectos de conservación."],
        ["Escuche la entrevista completa aquí: [link a la entrevista]"]
      ],
      videoUrl: "",
      videoAlt: "",
      videodescription: "",
      gallery: [],
      iframe: [],
    },
    {
      id: 3,
      title: "Entrevista a Bellazmín Arenas Quintana, coordinadora de la Unidad de Proyección Social de la Universidad Autónoma de Manizales",
      category: "Entrevista",
      date: "2024-07-16",
      shortdescription: "Entrevista a Bellzmín Arenas Quintana, hablando sobre el papel de la universidad en la proyección social y el compromiso con la comunidad.",
      bannerUrl: "https://www.tropicanafm.com/wp-content/uploads/2022/02/GettyImages-1301663422.jpg",
      bannerAlt: "Entrevista a Bellazmín Arenas Quintana",
      bannerdescription: "Foto | Tropicana",
      articlesocialmedia: {
        facebook: "Facebook",
        twitter: "Twitter",
        instagram: "",
        linkedin: "",
        youtube: "",
        telegram: "",
        whatsapp: "",
        email: ""
      },
      media: {
        name: "Tropicana",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Tropicana_Colombia_logo.png",
        logoAlt: "Tropicana",
        socialmedia: {
          web: "",
          facebook: "",
          twitter: "",
          instagram: "",
          linkedin: "",
          youtube: "",
        }, 
      },
      subtitle: [
        ["Entrevista a Bellzmín Arenas Quintana, coordinadora de la Unidad de Proyección Social de la Universidad Autónoma de Manizales."]
      ],
      audiotitle: "",
      audioUrl: "",
      titledescription: "Bellzmín Arenas Quintana, coordinadora de la Unidad de Proyección Social, comparte su visión sobre las iniciativas de la universidad para involucrarse con la comunidad y contribuir al desarrollo social.",
      paragraph: [
        ["Durante la entrevista, Bellzmín Arenas Quintana habló sobre el compromiso de la universidad con la responsabilidad social y cómo juega un papel crucial en abordar las necesidades de la comunidad local. La Unidad de Proyección Social se centra en desarrollar proyectos que no solo mejoren el aprendizaje académico, sino que también proporcionen contribuciones significativas a la sociedad."],
        ["Quintana destacó varios proyectos en curso, incluyendo programas de divulgación educativa, iniciativas de sostenibilidad ambiental y asociaciones con organizaciones locales para fomentar el desarrollo comunitario. Subrayó la importancia de integrar el conocimiento académico con aplicaciones prácticas para crear un impacto positivo."],
        ["La entrevista también abordó los planes futuros para expandir las actividades de la unidad y mejorar las colaboraciones con diversos actores, incluyendo ONGs, agencias gubernamentales y socios del sector privado. Quintana expresó optimismo sobre el potencial de estas iniciativas para crear un cambio duradero y mejorar la calidad de vida de las personas en la región."]
      ],
      videoUrl: "",
      videoAlt: "",
      videodescription: "",
      gallery: [],
      iframe: [],
    },
    {
      id: 4,
      title: "RCN Radio Manizales 1.060 AM transmitió en vivo sobre el Congreso Internacional de Organizaciones Ambientales",
      category: "Transmisión",
      date: "2024-07-12",
      shortdescription: "RCN Radio Manizales transmitió en vivo una discusión sobre el próximo Congreso Internacional de Organizaciones Ambientales.",
      bannerUrl: "https://example.com",
      bannerAlt: "RCN Radio Manizales",
      bannerdescription: "Foto | RCN Radio",
      articlesocialmedia: {
        facebook: "Facebook",
        twitter: "Twitter",
        instagram: "",
        linkedin: "",
        youtube: "",
        telegram: "",
        whatsapp: "",
        email: ""
      },
      media: {
        name: "RCN Radio Manizales",
        logoUrl: "https://example.com",
        logoAlt: "RCN Radio Manizales",
        socialmedia: {
          web: "",
          facebook: "",
          twitter: "",
          instagram: "",
          linkedin: "",
          youtube: "",
        }, 
      },
      subtitle: [
        ["RCN Radio Manizales 1.060 AM transmitió en vivo una discusión sobre el próximo Congreso Internacional de Organizaciones Ambientales."]
      ],
      audiotitle: "",
      audioUrl: "https://example.com",
      titledescription: "Victoria Salazar Gil, coordinadora de la Especialización en Formulación, Gerencia y Evaluación de Proyectos de Desarrollo y coordinadora de práctica social, compartió su perspectiva sobre la importancia del Congreso para las organizaciones ambientales y la comunidad.",
      paragraph: [
        ["Victoria Salazar Gil habló sobre el papel del congreso en fomentar la colaboración entre organizaciones ambientales y actores interesados. Resaltó la importancia de eventos como este para promover la conciencia, compartir conocimientos y desarrollar iniciativas conjuntas para abordar los desafíos ambientales."],
        ["Salazar Gil enfatizó que el congreso brindará una plataforma para que las organizaciones presenten sus proyectos, busquen asociaciones y exploren oportunidades de financiamiento. El evento tiene como objetivo fortalecer la red de organizaciones ambientales y mejorar su capacidad para implementar proyectos de impacto."],
        ["La transmisión en vivo también cubrió los temas clave del congreso, incluyendo fuentes de financiamiento para proyectos ambientales, conservación de la biodiversidad, innovación en sostenibilidad, educación y discusiones de políticas. Se espera que el evento atraiga a una audiencia diversa, incluyendo investigadores, formuladores de políticas y activistas."]
      ],
      videoUrl: "",
      videoAlt: "",
      videodescription: "",
      gallery: [],
      iframe: [],
    },
    {
      id: 5,
      title: "Internacionalización: 1er Congreso Internacional de Organizaciones Ambientales con sede en la UAM",
      category: "Internacionalización",
      date: "2024-07-19",
      shortdescription: "La Universidad Autónoma de Manizales (UAM) será la sede del 1er Congreso Internacional de Organizaciones Ambientales, un evento histórico que posicionará a Manizales como la capital mundial en la lucha contra el cambio climático y la conservación ambiental.",
      bannerUrl: "https://example.com",
      bannerAlt: "Conferencia UAM",
      bannerdescription: "Foto | UAM",
      articlesocialmedia: {
        facebook: "Facebook",
        twitter: "Twitter",
        instagram: "",
        linkedin: "",
        youtube: "",
        telegram: "",
        whatsapp: "",
        email: ""
      },
      media: {
        name: "UAM",
        logoUrl: "https://example.com",
        logoAlt: "Universidad Autónoma de Manizales",
        socialmedia: {
          web: "",
          facebook: "",
          twitter: "",
          instagram: "",
          linkedin: "",
          youtube: "",
        }, 
      },
      subtitle: [
        ["La Universidad Autónoma de Manizales (UAM) será la sede del 1er Congreso Internacional de Organizaciones Ambientales, un evento histórico que posicionará a Manizales como la capital mundial en la lucha contra el cambio climático y la conservación ambiental."]
      ],
      audiotitle: "",
      audioUrl: "https://example.com",
      titledescription: "Del 20 al 23 de agosto de 2024, cerca de 100 organizaciones ambientales se reunirán en Manizales, Caldas, gracias a la colaboración entre Awaq Estaciones Biológicas, la Universidad Autónoma de Manizales y la Sociedad de Doctores e Investigadores de Colombia (SoPhIC).",
      paragraph: [
        ["Este 1er Congreso Internacional de Organizaciones Ambientales tiene como objetivo principal unir esfuerzos entre organizaciones gestoras de proyectos, expertos en sostenibilidad y entidades públicas y privadas, con el fin de crear un futuro más verde y consciente. El encuentro se enfocará en:"],
        ["- Generar alianzas estratégicas.", "- Desarrollar soluciones innovadoras para combatir el cambio climático.", "- Fomentar la colaboración entre universidades, organismos públicos y empresas privadas."],
        ["Líneas temáticas del congreso:"],
        ["- **Fuentes de Financiación de Proyectos Ambientales**: Identificación y acceso a fondos y recursos para apoyar proyectos de sostenibilidad.", "- **Conservación de la Biodiversidad**: Proyectos y prácticas para preservar y restaurar ecosistemas.", "- **Innovación en Sostenibilidad**: Desarrollo y aplicación de tecnologías verdes.", "- **Educación y Sensibilización**: Talleres y conferencias para educar y movilizar a la comunidad global.", "- **Políticas y Regulaciones**: Discusión sobre políticas públicas y regulaciones que apoyen la sostenibilidad ambiental."],
        ["Durante el congreso, se firmará un manifiesto que será presentado al Consejo Económico y Social de las Naciones Unidas (ECOSOC) por Awaq ONGD en su calidad de miembro consultivo. Este documento reflejará nuestro compromiso y las acciones necesarias para impulsar la transición hacia un mundo más sostenible."],
        ["Los interesados se pueden registrar [aquí](https://example.com)."],
        ["**¿Por qué asistir al 1er Congreso Internacional de Organizaciones Ambientales?**"],
        ["- Forja alianzas poderosas: Conecta con universidades, organismos públicos y entidades privadas dedicadas a la sostenibilidad ambiental.", "- Innova y colabora: Descubre soluciones vanguardistas y colabora en proyectos que impactarán el futuro de la conservación.", "- Sé parte de un movimiento: Únete a una comunidad de personas y organizaciones apasionadas por hacer una diferencia real."],
        ["No te pierdas esta oportunidad única de ser parte de un movimiento que definirá el futuro de la conservación ambiental en Colombia y más allá."]
      ],
      videoUrl: "",
      videoAlt: "",
      videodescription: "",
      gallery: [],
      iframe: [],
    },
  ],
  };
  export default ContentSaladePrensa;