const ContenContactForm = {
  en: {
  registrotitle: "PRE-REGISTER",
  registrosubtitle: "We are conducting the pre-registration process for organizations that wish to participate in the congress.",
  registrosubtitle2: "The formalization of registration will take place in the second half of May, on which date we will contact you again to complete the procedures.",
  indicationform: "In the 'Write your comment' field, tell us if you have funding for travel, accommodation, and meals, or if you would need financial support.",
  notaform: "Note: Pre-registration does not guarantee attendance until formalization is completed.",
  notaform2l1: "Your voice is priceless!!",
  notaform2l2: "Attendance at the congress is free for pre-registered organizations",
  textHome: "HOME",
  messajePage: "Thank you for your Interest in the International Congress of Environmental Organizations",
  messajePage2: "We are processing your request, we will contact you shortly.",
  messajePage3: "The Contact Form has been sent successfully.",
  messajePage4: "The Pre-registration Form has been sent successfully.",
  language: "Spanish",
  title: "Do You Have Questions?",
  subtitle: "We Have Answers!!!",
  subtitle2: "Leave us a message and we will help you resolve any questions as soon as possible.",
  paragrph: "Our Human Team will attend to your inquiries, Contact Us!!",
  inputName: "Name",
  inputSurName: "Last Name",
  inputEmail: "Email",
  inputPhone: "Phone Number",
  inputSubject: "Subject",
  inputDescription: "Write your inquiry here...",
  inputCommentary: "Write your comments here...",
  companyName: "Organization / Company Name",
  role: "Role within the Organization/Company",
  country: "Country",
  department: "Department / State",
  city: "City",
  sendTo: "Send to",
  textTerms: "I have read and accept the",
  textTermsLink: " privacy policy",
  textRequired: " (Required)",
  TextMarketing: "I accept to receive email communications from Awaq ONGD",
  textButton: "Send",
  sectionRed: [
    {
      name: "Library",
      link: "https://www.somosawaq.org/transparency",
      text: "Dive into our Annual Reports, our Code of Ethics, and our Master Plan, among other documents.",
      img: "https://somosawaqblob.blob.core.windows.net/somosawaq/library.png",
    },
    {
      name: "LinkedIn",
      link: "https://www.linkedin.com/company/awaq-ongd",
      text: "Get to know our history through the publications and posts we regularly share with our followers.",
      img: "https://somosawaqblob.blob.core.windows.net/somosawaq/LinkedIn.png",
    },
    {
      name: "Facebook",
      link: "https://www.facebook.com/somosawaq",
      text: "Enjoy the multimedia visualization of Awaq Biological Stations expressed on this social network.",
      img: "https://somosawaqblob.blob.core.windows.net/somosawaq/Facebook.png",
    },
  ],
  type: "Account type",
  options: {
    none: "--None--",
    universities: "Universities",
    organizations: "Organizations",
    publicAdministrations: "Public Administrations",
    privateCompanies: "Private Companies",
  },
},
  es: {
    registrotitle:"PREINSCRIBETE",
    registrosubtitle:"Estamos realizando el proceso de preinscripción de las organizaciones que desean estar presentes en congreso.",
    registrosubtitle2:"La formalización de la inscripción se realizará en la segunda quincena de Mayo, fecha en la cual os volveremos a contactar para formalizar los tramites.",
    indicationform:"En el campo Escribe tus comentarios cuéntanos si cuéntas con financiación para el viaje , alojamiento y manutención o por el contario precisarías soporte económico.",
    notaform:"Nota: La preinscripción no garantiza la asistencia al mismo hasta no tener completada la formalización.",
    notaform2l1:"¡¡Tu voz no tiene precio!!",
    notaform2l2:"La asistencia al congreso es gratuita para las organizaciones preinscritas",
    textHome: "INICIO",
    messajePage: "Gracias por tu Interés en el Congreso Internacional de Organizaciones Ambientales",
    messajePage2: "Estamos procesando tu solicitud, en breve nos pondremos en contacto contigo.",
    messajePage3: "El formulario de Contacto ha sido enviado con éxito.",
    messajePage4: "El formulario de Pre-inscripción ha sido enviado con éxito.",
    language: "Spanish",
    title: "¿Tienes Preguntas?",
    subtitle: "¡¡¡ Nosotros Tenemos Respuestas !!!",
    subtitle2: "Déjanos un mensaje y a la mayor brevedad posible te ayudaremos a resolver cualquier duda. ",
    paragrph:
      "Nuestro Equipo Humano Atendera tus Consultas, Contacta con Nosotros!!",
    inputName: "Nombre",
    inputSurName: "Apellidos",
    inputEmail: "Correo Electronico",
    inputPhone: "Número de Teléfono",
    inputSubject: "Asunto",
    inputDescription: "Escribe tu consulta aquí...",
    inputCommentary: "Escribe tus comentarios aquí...",
    companyName: "Nombre de la Organización / Compañía",
    role: "Puesto dentro de la Organización / Compañía",
    country: "País",
    department: "Departamento/Estado",
    city: "Ciudad / Municipio",
    sendTo: "Envia a",
    textTerms: "He leído y acepto las",
    textTermsLink: " política de privacidad",
    textRequired: " (Requerido)",
    TextMarketing:
      "Acepto recibir comunicaciones por correo electrónico de Awaq ONGD",
    textButton: "Enviar",
    sectionRed: [
      {
        name: "Librería",
        link: "https://www.somosawaq.org/transparency",
        text: "Sumérgete en nuestras Memorias Anuales, nuestro Código Ético y nuestro Plan Director, entre otros documentos.",
        img: "https://somosawaqblob.blob.core.windows.net/somosawaq/library.png",
      },
      {
        name: "LinkedIn",
        link: "https://www.linkedin.com/company/awaq-ongd",
        text: "Conoce nuestra historia a través de las publicaciones y posts que compartimos regularmente con nuestros seguidores.",
        img: "https://somosawaqblob.blob.core.windows.net/somosawaq/LinkedIn.png",
      },
      {
        name: "Facebook",
        link: "https://www.facebook.com/somosawaq",
        text: "Disfruta de la visualización multimedia de las Estaciones Biológicas Awaq expresada en esta red social.",
        img: "https://somosawaqblob.blob.core.windows.net/somosawaq/Facebook.png",
      },
    ],
    type: "Tipo de cuenta",
    options: {
      none: "--Ninguno--",
      universities: "Universidades",
      organizations: "Organizaciones",
      publicAdministrations: "Administraciones Públicas",
      privateCompanies: "Empresas Privadas",
    },
  },
};

export default ContenContactForm;
